Fix memory leak due to listeners
postmanlabs/postman-sandbox pull request #884
Opened 2022-12-23 12:24 UTC by KiraElric007

Removed execution.console.{{id}} and execution.cookies.{{id}} listeners after an execution is completed to free up heap memory.

2022-12-27 14:06 UTC, postfrzero commented
Let's get the review started but let's not merge it just yet. We'll have to evaluate how we'll roll this out to users and merging this into the stable branch before doing so would be premature.

2023-01-04 08:02 UTC, codenirvana requested changes

2023-01-04 08:02 UTC, codenirvana commented on lib/postman-sandbox.js
> +
```suggestion
            this.removeAllListeners(consoleEventName);
```

2023-01-19 09:50 UTC, codenirvana approved these changes

2023-01-19 09:50 UTC, merged