Deprecate legacy sandbox APIs
postmanlabs/postman-sandbox pull request #987
Opened 2024-03-15 10:09 UTC by coditva

2024-03-15 10:09 UTC, coditva commented on types/sandbox/prerequest.d.ts
> +declare var responseCookies: {};
Not sure why these still show up even after putting the exclude tag.

2024-03-26 06:07 UTC, codenirvana requested changes

2024-03-26 06:07 UTC, codenirvana commented on npm/utils/templates.js
> + * @deprecated Use pm.global instead
```suggestion
 * @deprecated Use pm.globals instead
```

2024-03-26 06:07 UTC, codenirvana commented on npm/utils/templates.js
> + * @deprecated Use require('tv4') instead
```suggestion
 * @deprecated Use require('ajv') instead
```

2024-04-01 08:46 UTC, codenirvana approved these changes

2024-04-01 08:46 UTC, merged